# 清新活力主题 (Fresh Vibes Theme)
fg = "#0077c0" # 深青灰文字（保证对比度）
bg = "#122d42" # #eaffd0 柔光绿背景

[month_til]
fg = "Rgb(149, 225, 211)" # #95e1d3 浅水蓝（非当前月）
italic = true             # 斜体表示非活跃月份

[month_head]
fg = "Rgb(252, 227, 138)" # #fce38a 奶油黄（月份标题）
bold = true
under_line = true         # 加下划线强调

[workday_adjacent]
fg = "Rgb(149, 225, 211)" # #95e1d3 60%透明度
transparent_bg = true     # 透明背景弱化相邻日期

[holiday_adjacent]
fg = "Rgb(243, 129, 129)" # #f38181 淡珊瑚红（相邻假日）
italic = true

[bottom_line]
fg = "Rgb(252, 227, 138)" # #fce38a 奶油黄分隔线
bold = true

[workday]
fg = "#c7eeff" # 深青灰文字（工作日）
bold = true

[holiday]
fg = "Rgb(243, 129, 129)" # #f38181 珊瑚红（假日）
bold = false

[focus_day]
fg = "Rgb(252, 227, 138)" # #fce38a 奶油黄（焦点日）
bg = "Rgb(243, 129, 129)" # #f38181 珊瑚红背景
bold = true
